export const DISMISS_MESSAGE = 'DISMISS_MESSAGE';

export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';

export const TYPING = 'TYPING';

export const CREATE_QUESTION_REQUEST = 'CREATE_QUESTION_REQUEST';
export const QUESTION_FAILURE = 'QUESTION_FAILURE';
export const CREATE_QUESTION_SUCCESS = 'CREATE_QUESTION_SUCCESS';
export const CREATE_QUESTION_DUPLICATE = 'CREATE_QUESTION_DUPLICATE';
export const INCREMENT_LIKE = 'INCREMENT_LIKE';
export const DECREMENT_LIKE = 'DECREMENT_LIKE';
export const GET_QUESTIONS = 'GET_QUESTIONS';
export const GET_QUESTIONS_REQUEST = 'GET_QUESTIONS_REQUEST';
export const GET_QUESTIONS_SUCCESS = 'GET_QUESTIONS_SUCCESS';
export const GET_QUESTIONS_FAILURE = 'GET_QUESTIONS_FAILURE';
export const QUESTION_TYPING = 'QUESTION_TYPING';
export const DESTROY_QUESTION = 'DESTROY_QUESTION';
export const REMOVE_TAG = 'REMOVE_TAG';

export const CREATE_ANSWER_REQUEST = 'CREATE_ANSWER_REQUEST';
export const CREATE_ANSWER_FAILURE = 'CREATE_ANSWER_FAILURE';
export const CREATE_ANSWER_SUCCESS = 'CREATE_ANSWER_SUCCESS';
export const DESTROY_ANSWER = 'DESTROY_ANSWER';


export const GET_COUNTS = 'GET_COUNTS';
export const GET_COUNTS_REQUEST = 'GET_COUNTS_REQUEST';
export const GET_COUNTS_SUCCESS = 'GET_COUNTS_SUCCESS';
export const GET_COUNTS_FAILURE = 'GET_COUNTS_FAILURE';

export const GET_AUTHENTICATED_USER = 'GET_AUTHENTICATED_USER';
export const GET_AUTHENTICATED_USER_FAILURE = 'GET_AUTHENTICATED_USER_FAILURE';
export const GET_AUTHENTICATED_USER_SUCCESS = 'GET_AUTHENTICATED_USER_SUCCESS';

export const TOGGLE_LOGIN_MODE = 'TOGGLE_LOGIN_MODE';
export const MANUAL_LOGIN_USER = 'MANUAL_LOGIN_USER';
export const LOGIN_SUCCESS_USER = 'LOGIN_SUCCESS_USER';
export const LOGIN_ERROR_USER = 'LOGIN_ERROR_USER';
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_SUCCESS_USER = 'SIGNUP_SUCCESS_USER';
export const SIGNUP_ERROR_USER = 'SIGNUP_ERROR_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_SUCCESS_USER = 'LOGOUT_SUCCESS_USER';
export const LOGOUT_ERROR_USER = 'LOGOUT_ERROR_USER';
